---
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
    - "**.js"
exclude_paths:
  - "node_modules/**"
  - ".idea/**"
  - "_book/**"
