language: node_js

node_js:
  - '4.4'
  - '5.11'
  - '6.4'

sudo: false

install:
  - travis_retry npm install

script:
  - npm test
  - npm run eslint
  - npm run jsinspect

notifications:
  slack: squeezerio:4ISMhZ6FBNpUYppy8kRK4uLf